blog/urls.py
from django.conf.urls import url
from django.urls import path, re_path, include
from . import views
from blog.views import PostsListView, PostDetailView
from django.conf.urls.static import static
from django.conf import settings


app_name = 'blog'

urlpatterns = [
    url(r'^$', PostsListView.as_view(), name='posts-list'),
    url(r'^accounts/', include('allauth.urls')),
    re_path(r'^(?P<slug>\w+)/$', PostsListView.as_view(), name='posts-list'),
    path('post/<slug:slug>/', PostDetailView.as_view(), name='post-detail'),

    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse
from django.utils.translation import ugettext as _


#TODO:
#   Image - отдельная модель многие ко многим(?)
# - Category image 
# - Post image
# - Fat Models, thin View, stupid Template!


class Category(models.Model):
    title = models.CharField('Заголовок', max_length=100)
    slug = models.SlugField(max_length=50, unique=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}'.format(self.title)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Tag(models.Model):
    title = models.CharField(max_length=20)
    slug = models.SlugField(max_length=50, unique=True)

    def __str__(self):
        return '{}'.format(self.title)
    
    def get_absolute_url(self):
        return reverse(kwargs={"slug": self.slug})
    
    class Meta:
        verbose_name = 'Тэг'
        verbose_name_plural = 'Тэги'


class Post(models.Model):
    title = models.CharField('Заголовок', max_length=150, db_index=True)
    text = models.TextField('Текст', blank=True, db_index=True)
    slug = models.SlugField(max_length=50, unique=True)
    tags = models.ManyToManyField(Tag, blank=True, related_name='posts')
    published_date = models.DateTimeField(blank=True, null=True)

    publishTrue = models.BooleanField(default=True, db_index=True, verbose_name=_('Publish'))
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.CharField('Краткое описание', max_length=250, blank=True)
    
    #!Изображение сохраняется, 
    #нужно вывести -> views 
    #и thumbnail -> admin
    img = models.ImageField(upload_to='media/images', 
                      blank=True, 
                      db_index=True,
                      verbose_name=_('Image'))

    def __str__(self):
        return '{}'.format(self.title)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={"slug": self.slug})

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ('-published_date',)


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField('Автор', max_length=100)
    text = models.TextField('Текст')
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save

    def __str__(self):
        return '{}'.format(self.text)

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Image(models.Model):
    name = models.CharField('Тайтл', max_length=25, unique=True)


class Sort(models.Model):
    pass


class Search(models.Model):
    pass

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text',)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from blog.models import Post, Comment 
from django.views.generic import ListView, DetailView
from .forms import CommentForm
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required

from .models import Category, Tag


class PostsListView(ListView):
    context_object_name = 'posts'
    model = Post
    template_name = 'blog/post_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostsListView, self).get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        return context

    def get_queryset(self):
        if self.kwargs.get('slug') == 'all':
            return self.model.objects.filter(publishTrue__exact=True)
        return self.model.objects.filter(tags__slug=self.kwargs.get('slug'),
                                         publishTrue__exact=True)


class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'blog/post_detail.html'

    def get_object(self, queryset=None):
        slug_ = self.kwargs.get("slug")
        return get_object_or_404(Post, slug=slug_)


def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('post_detail', pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('post_detail', pk=comment.post.pk)

blog/templates/blog/add_comment_to_post.html
{% extends 'base.html' %}

{% block content %}
    <h1>Новый комментарий</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-primary">Отправить</button>
    </form>
{% endblock %}

blog/templates/blog/footer.html
<footer>
    <div class="tt-footer-default tt-color-scheme-02">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-9">
                    <div class="tt-newsletter-layout-01">
                        <div class="tt-newsletter">
                            <div class="tt-mobile-collapse">
                                <h4 class="tt-collapse-title">
                                    BE IN TOUCH WITH US:
                                </h4>
                                <div class="tt-collapse-content">
                                    <form id="newsletterform" class="form-inline form-default" method="post" novalidate="novalidate" action="#">
                                        <div class="form-group">
                                            <input type="text" name="email" class="form-control" placeholder="Enter your e-mail">
                                            <button type="submit" class="btn">JOIN US</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-auto">
                    <ul class="tt-social-icon">
                        <li><a class="icon-g-64" target="_blank" href="http://www.facebook.com/"></a></li>
                        <li><a class="icon-h-58" target="_blank" href="http://www.facebook.com/"></a></li>
                        <li><a class="icon-g-66" target="_blank" href="http://www.twitter.com/"></a></li>
                        <li><a class="icon-g-67" target="_blank" href="http://www.google.com/"></a></li>
                        <li><a class="icon-g-70" target="_blank" href="https://instagram.com/"></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="tt-footer-col tt-color-scheme-01">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-lg-12 text-center">
                    <h6 style="color:#303030; font-weight:700">In Code We Trust</h6>
                </div>

<!--                 <div class="col-md-6 col-lg-2 col-xl-3">
                    <div class="tt-mobile-collapse">
                        <h4 class="tt-collapse-title">
                            CATEGORIES
                        </h4>
                        <div class="tt-collapse-content">
                            <ul class="tt-list">
                                <li><a href="listing-collection.html">Women</a></li>
                                <li><a href="listing-collection.html">Men</a></li>
                                <li><a href="listing-collection.html">Accessories</a></li>
                                <li><a href="listing-collection.html">Shoes</a></li>
                                <li><a href="listing-collection.html">New Arrivals</a></li>
                                <li><a href="listing-collection.html">Clearence</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                
                <div class="col-md-6 col-lg-2 col-xl-3">
                    <div class="tt-mobile-collapse">
                        <h4 class="tt-collapse-title">
                            MY ACCOUNT
                        </h4>
                        <div class="tt-collapse-content">
                            <ul class="tt-list">
                                <li><a href="account_order.html">Orders</a></li>
                                <li><a href="page404.html">Compare</a></li>
                                <li><a href="page404.html">Wishlist</a></li>
                                <li><a href="login.html">Log In</a></li>
                                <li><a href="create-account.html">Register</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                
                <div class="col-md-6 col-lg-4 col-xl-3">
                    <div class="tt-mobile-collapse">
                        <h4 class="tt-collapse-title">
                            ABOUT
                        </h4>
                        <div class="tt-collapse-content">
                            <p>
                                Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore. Lorem ipsum dolor sit amet conse ctetur adipisicing elit, seddo eiusmod tempor incididunt ut labore etdolore.
                            </p>
                        </div>
                    </div>
                </div>
                
                <div class="col-md-6 col-lg-4 col-xl-3">
                    <div class="tt-newsletter">
                        <div class="tt-mobile-collapse">
                            <h4 class="tt-collapse-title">
                                CONTACTS
                            </h4>
                            <div class="tt-collapse-content">
                                <address>
                                    <p><span>Address:</span> 2548 Broaddus Maple Court Avenue, Madisonville KY 4783, United States of America</p>
                                    <p><span>Phone:</span> +777 2345 7885;  +777 2345 7886</p>
                                    <p><span>Hours:</span> 7 Days a week from 10 am to 6 pm</p>
                                    <p><span>E-mail:</span> <a href="mailto:info@mydomain.com">info@mydomain.com</a></p>
                                </address>
                            </div>
                        </div>
                    </div>
                </div> -->

            </div>
        </div>
    </div>


</footer>
<a href="#" class="tt-back-to-top">BACK TO TOP</a>
<!-- modal (ModalSubsribeGood) -->
<div class="modal  fade"  id="ModalSubsribeGood" tabindex="-1" role="dialog" aria-label="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xs">
        <div class="modal-content ">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="icon icon-clear"></span></button>
            </div>
            <div class="modal-body">
                <div class="tt-modal-subsribe-good">
                    <i class="icon-f-68"></i> You have successfully signed!
                </div>
            </div>
        </div>
    </div>
</div>

blog/templates/blog/index.html
{% extends "base.html" %}

{% block content %}
<div>
    <h2>My first App!</h2>
</div>
<div clsass="posts">
    {% for post in posts %}
        {{ post }}
    {% endfor %}
</div>
{% endblock content %}

blog/templates/blog/navbar.html
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark" role="navigation">
        
        <a class="navbar-brand" href="/">
        {% load static %}
            <img src="{% static 'images/logo.png' %}" width="30" height="30" alt="logo">
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="#">Обзоры <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Туториалы</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Книги</a>
            </li>
        </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
    </form>
  </div>
</nav>

blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block content %}

<div id="tt-pageContent">
	<div class="container-indent">
		<div class="container container-fluid-custom-mobile-padding">
			<div class="row justify-content-center">
				<div class="col-xs-12 col-md-10 col-lg-8 col-md-auto">

                    <p>{{ post.published_date }}</p>
                    <h2>{{ post.title }}</h2>
                    <div><img src="{{ post.image.url | safe }}"/></div>
                    <p>{{ post.text | safe }}</p>

    <div class="post-meta" style="margin-top:5%;">
        <p>Теги:{% for tag in post.tags.all %}<a href="/tag/{{tag.id}}"> {{tag}}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</p>
	</div>
    <hr>
{% for comment in post.comments.all %}
    {% if user.is_authenticated or comment.approved_comment %}
    <div class="comment">
        <div class="date">
            {{ comment.created_date }}
            {% if not comment.approved_comment %}
                <a class="btn btn-default" href="{% url 'blog:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                <a class="btn btn-default" href="{% url 'blog:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
            {% endif %}
        </div>
        <strong>{{ comment.author }}</strong>
        <p>{{ comment.text|linebreaks }}</p>
    </div>
    {% endif %}
{% empty %}
    <p>Здесь комментариев ещё нет :(</p>
{% endfor %}
    <a class="btn btn-primary" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Добавить комментарий</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div id="tt-pageContent">
    <div class="container-indent">
        <div class="container">
            <h1 class="tt-title-subpages noborder">Python Daily Journal</h1>
            <div class="tt-blog-masonry">
                <div class="tt-filter-nav">

                    <a class="button {% if view.kwargs.slug == 'all' %}active{% endif %}"
                       href="{% url 'blog:posts-list' 'all' %}" >ALL</a>

                    {% for tag in tags %}
                        <a class="button {% if view.kwargs.slug == tag.slug %}active{% endif %}"
                           href="{% url 'blog:posts-list' tag.slug %}">{{ tag|upper }}</a>
                    {% endfor %}
                    
                </div>
        <div class="tt-blog-init tt-grid-col-3 tt-layout-01-post tt-add-item">
            {% for post in posts %}
                    <div class="element-item">
                        <div class="tt-post">
                            <div class="tt-post-img">
                                <a href="{{ post.get_absolute_url }}">
                                    <img src="{% static 'images/code.jpg' %}" alt="">
                                </a>
                            </div>
                            <div class="tt-post-content">
                                <div class="tt-background"></div>
                                <div class="tt-tag">
                                    {% for tag in post.tags.all %}<a href="/tag/{{tag.id}}"> {{tag}}</a>{% if not forloop.last %}, {% endif %}{% endfor %}
                                </div>
                                    <h2 class="tt-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                                <div class="tt-description">{{ post.description }}</div>
                                <div class="tt-meta">
                                    <div class="tt-autor">{{ post.created }}</div>
                                
                                    <div class="tt-comments"><a href="#"><i class="tt-icon icon-f-88"></i>7</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
            {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

blog/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block head_title %} {% endblock %}Django blog</title>
    <meta name="keywords" content="Django">
    <meta name="description" content="Django blog">
    <meta name="author" content="taurus">
    <link rel="shortcut icon" href="favicon.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/theme.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/siimple@3.3.1/dist/siimple.min.css">
</head>
<body>
{% include 'blog/header.html' %}

<div class="container">
    {% block content %} Empty page {% endblock %}
</div>

{% include 'blog/footer.html' %}

<!--JavaScript -->
<script src="{% static 'external/jquery/jquery.min.js' %}"></script>
<script src="{% static 'external/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'external/bootstrap-datepicker/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'external/slick/slick.min.js' %}"></script>
<script src="{% static 'external/panelmenu/panelmenu.js' %}"></script>
<script src="{% static 'external/isotope/imagesloaded.js' %}"></script>
<script src="{% static 'external/isotope/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'external/lazyLoad/lazyload.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<!-- form validation and sending to mail -->
<script src="{% static 'external/form/jquery.form.js' %}"></script>
<script src="{% static 'external/form/jquery.validate.min.js' %}"></script>
<script src="{% static 'external/form/jquery.form-init.js' %}"></script>

</body>
</html>

templates/blog/header.html
<div class="jumbotron">
    <div class="container-fluid">
        <h1 class="display-4">Fluid jumbotron</h1>
        <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
        <ul class="nav">
            <li><a href="{% url 'list' %}" class="">Список постов</a></li>
        </ul>
    </div>
</div>

templates/blog/index.html
{% extends "blog/base.html"%}

{% block content %}
<div>
    <h2>My first App!</h2>
</div>
<div clsass="posts">
    {% for post in posts %}
        {{ post }}
    {% endfor %}
</div>
{% endblock content %}

templates/blog/post_detail.html
{% extends "blog/base.html"%}

{% block content %}
    <p>{{ post.published_date }}</p>
    <h2>{{ post.title }}</h2>
    <p>{{ post.text }}</p>
{% endblock %}

templates/blog/post_list.html
{% extends "blog/base.html"%}

{% block content %}
    {% for post in object_list %}

            <div class="card" style="width: 18rem;">
            {% load static %}
                <img src="{% static 'images/3.png' %}" alt="Card Two" class="card-img-top">
            <div class="card-body">
                <h5 class="card-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h5>
                <p class="card-text">{{ post.content }}</p>
                <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Читать</a>
            </div>
            </div>

    {% empty %}
        <p>Нет постов</p>
    {% endfor %}

{% endblock %}